---
- name: Copy Helm chart to Kubernetes master node
  hosts: kubernetes-master
  tasks:
    - name: Copy Helm chart directory to Kubernetes master node
      ansible.builtin.copy:
        src: ./backenddeply
        dest: /home/ubuntu/
        remote_src: no
      delegate_to: kubernetes-master  # Execute the task on the Kubernetes master node
- name: Upgrade or install Helm chart
  hosts: kubernetes-master
  tasks:
    - name: Upgrade or install Helm chart
      kubernetes.core.helm:
        name: back-end
        chart_ref: /home/ubuntu/backenddeply
        release_namespace: default  # Specify the namespace where the release should be installed or upgraded
        release_state: present
        force: yes
